server:
  port: 3000
spring:
  application:
    name: auth-server
  cloud:
    discovery:
      enabled: true
  redis:
    host: localhost
    port: 6379

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
  social:
    filter-processes-url: /social
    wechat:
      app-id: wx8a47a66e22296c62
      app-secret: deb57af7ec1753a2668889e74b34b789

eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
##安全配置
#security:
#  #oauth2配置
#  oauth2:
#    resource:
#      filter-order: 3
