server:
  port: 3000
spring:
  application:
    name: auth-server
  cloud:
    discovery:
      enabled: true
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/
##安全配置
#security:
#  #oauth2配置
#  oauth2:
#    resource:
#      filter-order: 3
system:
  #客户端配置
  social:
    filterProcessesUrl: /qqLogin
    weixin:
      app-id: wx8a47a66e22296c62
      app-secret: deb57af7ec1753a2668889e74b34b789