server:
  port: 9098
spring:
  application:
    name: auth-server
  cloud:
    discovery:
      enabled: true
  redis:
    host: localhost
    port: 6379
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:8761/eureka/